theme: minima
title: Alex's blog
future: true
paginate: 12

title: Alex's blog
author:
  name: Alex Telford
  email: atelford@crai.com
description: > # this means to ignore newlines until "show_excerpts:"
  Personal site for posts about my interests: the biotech industry, medicine, molecular biology, neuroscience, biorisk, science, consciousness, AI, innovation, decision making, philosophy, games, sci-fi, probability, and forecasting (among other things). I write to learn, mostly about biotech.
business_description: >
    For business enquiries: My day job is a commercial strategy consultant for the life sciences industry. If you're working on a tricky commercialization problem, need to better understand a market, or just want an outside opinion you can contact me on my work email <a class="u-email" href="mailto:atelford@crai.com">here</a> or on linkedin, perhaps we can help!

show_excerpts: false # set to true to show excerpts on the homepage


# Minima date format
minima:
  date_format: "%Y-%m-%d"

  # generate social links in footer
  social_links:
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/alex-telford-468348b0/" }
    - { platform: twitter,        user_url: "https://twitter.com/atelfo" }
    - { platform: rss,            user_url: "https://atelfo.github.io/feed.xml" }

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima
  
plugins:
 - jekyll-seo-tag
 - jekyll-feed

feed:
 excerpt_only: true