theme: minima
title: Alex's blog
future: true
description: Life sciences consultant.<br><br>Interested in the biotech industry, medicine, molecular biology, neuroscience, biorisk, science, consciousness, AI, innovation, decision making, philosophy, games, sci-fi, probability and forecasting (among other things).<br><br>I write to learn, mostly about biotech.
paginate: 5000