theme: jekyll-theme-minimal
title: @musings
description: <br>Life sciences consultant.</br><br>Interested in medicine, molecular biology, neuroscience, philosophy, games, sci-fi, probability.<br>I write to learn.</br>