theme: jekyll-theme-minimal
title: Alex's blog
description: Life sciences consultant.<br>Interested in medicine, molecular biology, neuroscience, philosophy, games, sci-fi, probability.<br>I write to learn.