theme: jekyll-theme-minimal
title: Alex Telford's blog
description: Life sciences consultant. Interested in medicine, molecular biology, neuroscience, philosophy, games, sci-fi, probability. I write to learn.