theme: jekyll-theme-minimal
title: Alex's blog
description: Life sciences consultant.<br><br>Interested in the biotech industry, medicine, molecular biology, neuroscience, biorisk, science, consciousness, AI, innovation, decision making, philosophy, games, sci-fi, probability and forecasting (among other things).<br>I write to learn, mostly about biotech.